import Header from '../shared/widgets';
import Footer from '../shared/widgets/Footer';
import BreadCrumb from './breadcrumb';
import './global.css';
import SignUpBanner from './home-page/signupbanner/SignUpBanner';
import Providers from './Providers';
import { Toaster } from 'react-hot-toast';
import { AuthProvider } from './auth/callback/AuthContext'; // don't use useAuth here
import { Poppins, Roboto } from 'next/font/google';
import AuthUIWrapper from '../app/components/AuthUIWrapper'; // 👈 new client component

export const metadata = {
  title: 'Welcome to user-ui',
  description: 'Generated by create-nx-workspace',
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  variable: '--font-roboto',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} ${poppins.variable}`} suppressHydrationWarning>
        <AuthProvider>
          <Providers>
            <Header />
            <BreadCrumb />
            <div className="layout-wrapper">{children}</div>
            <SignUpBanner />
            <Footer />
            <Toaster position="top-right" reverseOrder={false} />
            <AuthUIWrapper /> {/* 👈 moved client logic here */}
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
