version: "3.8"

services:
  user-service:
    build: ../../apps/user-service
    ports:
      - "3000:3000"
    env_file:
      - ./infra/docker/.env
    depends_on:
      - postgres
      - redis
      - kafka
      - minio

  product-service:
    build: ../../apps/product-service
    ports:
      - "3001:3001"
    env_file:
      - ./infra/docker/.env
    depends_on:
      - postgres
      - kafka

  order-service:
    build: ../../apps/order-service
    ports:
      - "3002:3002"
    env_file:
      - ./infra/docker/.env
    depends_on:
      - postgres
      - kafka

  rating-service:
    build: ../../apps/rating-service
    ports:
      - "3003:3003"
    env_file:
      - ./infra/docker/.env
    depends_on:
      - postgres
      - kafka

  email-service:
    build: ../../apps/email-service
    ports:
      - "3004:3004"
    env_file:
      - ./infra/docker/.env
    depends_on:
      - kafka

  payment-service:
    build: ../../apps/payment-service
    ports:
      - "3005:3005"
    env_file:
      - ./infra/docker/.env
    depends_on:
      - postgres
      - kafka

  search-service:
    build: ../../apps/search-service
    ports:
      - "3006:3006"
    env_file:
      - ./infra/docker/.env
    depends_on:
      - kafka

  cart-service:
    build: ../../apps/cart-service
    ports:
      - "3007:3007"
    env_file:
      - ./infra/docker/.env
    depends_on:
      - redis
      - kafka

  admin-service:
    build: ../../apps/admin-service
    ports:
      - "3008:3008"
    env_file:
      - ./infra/docker/.env
    depends_on:
      - postgres
      - kafka

  invoice-service:
    build: ../../apps/invoice-service
    ports:
      - "3009:3009"
    env_file:
      - ./infra/docker/.env
    depends_on:
      - postgres
      - kafka
      - minio

  analytics-service:
    build: ../../apps/analytics-service
    ports:
      - "3010:3010"
    env_file:
      - ./infra/docker/.env
    depends_on:
      - kafka

  vendor-service:
    build: ../../apps/vendor-service
    ports:
      - "3011:3011"
    env_file:
      - ./infra/docker/.env
    depends_on:
      - postgres
      - kafka

env_file:
  - ./infra/docker/.env
