apiVersion: v1
kind: Secret
metadata:
  name: admin-service-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_IzRrx7gaLtp2@ep-icy-smoke-a1cyzmap-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  JWT_SECRET: "psyrim3ReSNikbVHwq/R624osFaIpjxGjt8HxNqUFAg="
  MINIO_ACCESS_KEY: "minio"
  MINIO_SECRET_KEY: "minio123"
  STRIPE_PAYMENT_SECRET_KEY: "sk_test_51RuUTuAWKx0IxXL3o8UQBImCdy2LHmPAi2ecF1kU4G7uJWddWFWcQ4IoDRGL8T7VXAqGnaziiIvxZWaCHZu4ERxt00FG5JmmAF"
  STRIPE_WEBHOOK_SECRET: "whsec_0e937222eb0bd974f0dc6619d1ba9b349f4eb62619aafe738c0baa6545727b92"
