replicaCount: 1

image:
  repository: email-service
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: NodePort
  port: 3004
  nodePort: 3004

ingress:
  enabled: true
  className: 'nginx'
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: api.localhost
      paths:
        - path: /api/email-service/(.*)
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

# Non-sensitive config
env:
  - name: REDIS_HOST
    value: "localhost"
  - name: REDIS_PORT
    value: "6379"
  - name: MINIO_ENDPOINT
    value: "localhost"
  - name: MINIO_PORT
    value: "9000"
  - name: KAFKA_BROKERS
    value: "localhost:9092"

# Sensitive data from Kubernetes Secret
envFrom:
  - secretRef:
      name: email-service-secrets
